### ISSUE TITLE
No way of passing AMPQConnection instance to publisher/consumer

### ISSUE THREAD

**Issue by runeh** [ask/carrot#1]
The Connection argument to pub/con is a class, not an instance. If you're not using django, you can't pass AMPQConnection as the connection class, as that requires arguments when instanciated. (As a workaround, functools.partial works btw).

Should the connection be an instance, or should kwargs be passed on to the connection constructor or something?

**Comment by ask** [comment]
Backwards incompatible change: Have to instantiate AMQPConnection object before passing it to consumers/publishers. Closed by df8f0e447cd59cb75951895796f750396367fdb7
