### ISSUE TITLE
0.4.1 breaks easy_install

### ISSUE THREAD

**Issue by jcater** [ask/carrot#11]
jason@jason-mac:~$ sudo easy_install carrot
Searching for carrot
Reading http://pypi.python.org/simple/carrot/
Reading http://github.com/ask/carrot/
Best match: carrot 0.4.1
Downloading http://pypi.python.org/packages/source/c/carrot/carrot-0.4.1.tar.gz#md5=f512b78a24868e837adf5afd3cebdc7d
Processing carrot-0.4.1.tar.gz
Running carrot-0.4.1/setup.py -q bdist_egg --dist-dir /tmp/easy_install-xhJDTo/carrot-0.4.1/egg-dist-tmp-fzwd9g
error: README: No such file or directory

**Comment by ask** [comment]
Make sure README exists when reading long_description. Closed by 1de1e20b178aa27040575e571c4e5f7f9d7e72fd

**Comment by jcater** [comment]
You had typos.

```
diff --git a/setup.py b/setup.py
index dbaf433..e7f7296 100644
--- a/setup.py
+++ b/setup.py
@@ -73,7 +73,7 @@ for dirpath, dirnames, filenames in os.walk(src_dir):
 if os.path.exists("README"):
     long_description = codecs.open('README', "r", "utf-8").read()
 else:
-    long_descripiton = "See http://pypi.python.org/pypi/carrot"
+    long_description = "See http://pypi.python.org/pypi/carrot"

 setup(
     name='carrot',
@@ -101,5 +101,5 @@ setup(
         "Topic :: System :: Distributed Computing",
         "Topic :: Software Development :: Libraries :: Python Modules",
     ],
-    long_description=codecs.open('README', "r", "utf-8").read(),
+    long_description=long_description,
 )
```

**Comment by jcater** [comment]
You missed the typo in the else: (You transposed "pit" with "pti" in description

```
 else:
-    long_descripiton = "See http://pypi.python.org/pypi/carrot"
+    long_description = "See http://pypi.python.org/pypi/carrot"
```
