### ISSUE TITLE
Do you need django to generate the docs?

### ISSUE THREAD

**Issue by atkinson** [ask/carrot#19]
Hi there.
I don't know sphinx at all and I hope you can help me generate docs for carrot.
Do I need to be in a django project?

When I run:  sphinx-build ~/git/carrot/docs /opt/docs/carrot

It complains:

  File "/Users/rich/git/carrot/docs/conf.py", line 25, in <module>
    from django.conf import settings
ImportError: No module named django.conf

many thanks!!!!!!

**Comment by ask** [comment]
Closed by 9adeb491b62206d6f08e5765e6428331faaa21bc

You're right it shouldn't require Django. it's just a conf.py file template left over from my django projects! Thanks for finding it!

**Comment by atkinson** [comment]
Thanks... One more thing.

If you add this to your config.cfg:

[build_sphinx]
source-dir = docs
build-dir  = docs
all_files  = 1

you can build the docs by running:

python setup.py build_sphinx

Cheers!!
rich
