### ISSUE TITLE
carrot cannot used on python 2.4

### ISSUE THREAD

**Issue by ghost** [ask/carrot#20]
hi ask,

I think we should keep carrot compatible with python 2.4. It's worth and it's easy. currently I find only two places:

1). in setup.py  the use of any():

def is_unwanted_file(filename):
    return any([filename.endswith(skip_ext) for skip_ext in SKIP_EXTENSIONS])

2) File "/home/zhigang/lib/python2.4/site-packages/carrot-0.8.0-py2.4.egg/carrot/backends/pystomp.py", line 114
    ack = "auto" if no_ack else "client"
                  ^
SyntaxError: invalid syntax

please consider.

thanks,

zhigang

**Comment by ask** [comment]
I fixed these, tell me if there's any more.
Thanks for the help!

**Comment by ghost** [comment]
Extracting carrot-0.8.0-py2.4.egg to /home/zhigang/lib/python2.4/site-packages
  File "/home/zhigang/lib/python2.4/site-packages/carrot-0.8.0-py2.4.egg/carrot/backends/pystomp.py", line 157
    persistent = "true" if delivery_mode == 2 else "false"

**Comment by ghost** [comment]
hi, ask. I also find the celery package is not working on python 2.4. do you have a plan to port it?

**Comment by ask** [comment]
It's on the roadmap for celery 1.0, any help is very appreciated!
Apparently it's not that much that is missing, it has been done (but they didn't contribute the patches back)

**Comment by ghost** [comment]
celery is great project. I'll try to contribute if my project (using celery) progress well.

thanks ask!
