### ISSUE TITLE
carrot.messaging.establish_connection requires DjangoBrokerConnection

### ISSUE THREAD

**Issue by twillis** [ask/carrot#22]
along the same lines as the issue I reported earlier in celery, establish_connection uses DjangoBrokerConnection so if in celery you write a custom loader for the purpose of setting your configuration from some source other than django.conf, it will be ignored in the establish_connection method and will assume all the django settings configuration machinery has been stood up.

not sure what the right fix would be, maybe an optional param for the BrokerConnection defaulted to DjangoBrokerConnection ? just thinking out loud

**Comment by twillis** [comment]
I should never file issues when I should be sleeping. this is actually in celery. :)plz ignore

**Comment by ask** [comment]
ok, ignored :)
