### ISSUE TITLE
Python Queue module based backend doesn't work with iterconsume() or wait()

### ISSUE THREAD

**Issue by yosh** [ask/carrot#23]
iterconsume (and by extension, wait()) does:

```
self.backend.consume(limit=limit)
```

but backends/queue.py defines consumer as:

```
def consume(self, queue, no_ack, callback, consumer_tag):
```

so obviously it doesn't work. Not sure the best way to fix it, perhaps implement declare_consumer and stash the callback?

**Comment by pmclanahan** [comment]
bump

Just encountered this.  Want to use queue backend for tests.
