### ISSUE TITLE
Make a consumer wrapper that supports multiple routing keys.

### ISSUE THREAD

**Issue by ask** [ask/carrot#3]
This could be very useful.
Something like:

```
 >>> consumer = ConsumerSet(queue="myqueue", exchange="myex",
 ...                             routing_keys=["feed.#", "twitter.#", "tasks.#"])
 >>> message = consumer.fetch()
```

**Comment by ask** [comment]
This is fixed now with the help of Sean Creeley.

**Comment by acmeguy** [comment]
Can you please tell me how this is done now

**Comment by ask** [comment]
http://ask.github.com/carrot/reference/carrot.messaging.html

Carrot is being discontinued replaced by Kombu: http://github.com/ask/kombu
This is way easier in Kombu.

**Comment by acmeguy** [comment]
Hi, can you please elaborate a bit more on this? (It's not clear to me, looking at the Kombu docs, how to do this)?

Best regards, 
   -Stefan
