### ISSUE TITLE
pika backend calls basic_get with incorrect arguments

### ISSUE THREAD

**Issue by jpellerin** [ask/carrot#33]
raw_message = self.channel.basic_get(queue, no_ack=no_ack)

Pika expects the ticket # as the first positional argument. This line should be:

raw_message = self.channel.basic_get(queue=queue, no_ack=no_ack)

**Comment by ask** [comment]
pika backend calls basic_get with incorrect arguments. Closed by 2bda766c8171a064b33f7d140d29beada7784818. Thanks to jpellerin
