### ISSUE TITLE
Use guest/guest as username/password in README

### ISSUE THREAD

**Issue by btubbs** [ask/carrot#38]
I installed RabbitMQ and Carrot today to try them out, and found that I was getting an IOError when trying the example in Carrot's README.  After using 'guest' instead of 'test' for the username and password (as they do in the RabbitMQ tutorial at http://www.rabbitmq.com/tutorial-one-python.html), the example worked.  I'm on Ubuntu 10.04.  Not sure if the defaults are different in other RabbitMQ packages.

**Comment by ask** [comment]
Use vhost / and username/password guest/guest in README.  Closed by a8dc7b203d07cde5e5933346eb9780f47514c8c5

**Comment by ask** [comment]
Ah, but it's also using the virtual host `"test"`, not "/", so it's not describing the defaults.

I would recommend getting started with Kombu instead, as Carrot is not in maintenance only mode, and Kombu is much better and fixes many problems.

**Comment by ask** [comment]
Link to Kombu: http://github.com/ask/kombu

**Comment by btubbs** [comment]
Didn't know about Kombu.  Thanks!
