### ISSUE TITLE
message object class in Consumer.receive() is amqplib.client_0_8.basic_message.Message not carrot.backends.pyamqplib.Message

### ISSUE THREAD

**Issue by gcachet** [ask/carrot#4]
Consumer.receive() message is not wrapped into carrot.backends.pyamqplib.Message and thus does not have ack() or reject() methods. 

Therefore examples in README don't work.

**Comment by ask** [comment]
Ouch. Thanks a lot for catching that. I don't use the callbacks myself anymore as I couldn't get them to play nice with the multiprocessing module, but that's not an excuse, as I should've written unit tests for this. I'll open up another ticket for that.
