### ISSUE TITLE
TypeError: reject() got an unexpected keyword argument 'requeue'

### ISSUE THREAD

**Issue by gcachet** [ask/carrot#8]
```
File "/Users/gregoire/Documents/Projects/easionet/pip/src/carrot/carrot/backends/base.py", line 30, in reject
    return self.backend.reject(self.delivery_tag, requeue=False)
```

carrot.backends.pyamqplib.Message.reject() does not have the same signature than base carrot.backends.base.Message.reject()

**Comment by ask** [comment]
Backend.reject does not take requeue argument, that's what Backend.requeue is
for. Closed by 0349010c7cd1b6e4074aac316ea4e028f4aed0b6. Thanks to gregoirecachet

**Comment by gcachet** [comment]
Thanks for the fix. I'm using RabbitMQ, but the rejects aren't working. It seems like they aren't implemented yet and they throw an exception. Can you confirm? (I guessed you are using RabbitMQ from the README).

**Comment by ask** [comment]
Yeah, seems so: http://lists.rabbitmq.com/pipermail/rabbitmq-discuss/2009-January/003183.html 

Come to think about it, I don't have a real need for reject(), as any place I do use reject() there is an error that is basically unrecoverable. Even in the README example, in which if the data is malformed, it means either that the user didn't send the right message data format, or a message was routed to the wrong place. So I think I'll rather raise an exception there than use message.reject().

**Comment by gcachet** [comment]
I think there are 2 types of errors :
1/ a temporary error (for example, the db transaction can't be committed for concurrency issues) and the message should be resent later.
2/ a permanent error (bug in the code or in data format that happens every time). You won't get anything (unless you upgrade the consumer application) if you retry, so throw an error and drop the message from the queue. 

reject() is good for the first kind of errors. But I can log them and deal with them by hand right now.
